title: YouTube Music to Plex
description: Sync your YouTube Music playlists with Plex
theme: just-the-docs

# Logo in the header
logo: /assets/images/logo.png

# Footer
footer_content: "Support the project: <a href=\"https://www.buymeacoffee.com/jjdenhertog\">Buy Me a Coffee</a>"

# Enable search
search_enabled: true

# Color scheme
color_scheme: dark

# Exclude from Jekyll processing
exclude:
  - Gemfile
  - Gemfile.lock

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
